// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PauseAll() {
  return window['go']['main']['App']['PauseAll']();
}

export function PlayAll() {
  return window['go']['main']['App']['PlayAll']();
}

export function SeekAll(arg1) {
  return window['go']['main']['App']['SeekAll'](arg1);
}
