// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugPrint(arg1:string):Promise<void>;

export function FileDialog(arg1:string):Promise<void>;

export function GetIPs(arg1:number):Promise<Array<string>>;

export function PauseAll():Promise<void>;

export function PlayAll():Promise<void>;

export function ProcessFile(arg1:string,arg2:string):Promise<void>;

export function SeekAll(arg1:number):Promise<void>;
