// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DebugPrint(arg1) {
  return window['go']['main']['App']['DebugPrint'](arg1);
}

export function FileDialog(arg1) {
  return window['go']['main']['App']['FileDialog'](arg1);
}

export function GetIPs(arg1) {
  return window['go']['main']['App']['GetIPs'](arg1);
}

export function PauseAll() {
  return window['go']['main']['App']['PauseAll']();
}

export function PlayAll() {
  return window['go']['main']['App']['PlayAll']();
}

export function ProcessFile(arg1, arg2) {
  return window['go']['main']['App']['ProcessFile'](arg1, arg2);
}

export function SeekAll(arg1) {
  return window['go']['main']['App']['SeekAll'](arg1);
}
